---
- name: "Installer les prérequis pour Docker"
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: true
    cache_valid_time: 3600
  tags:
    - docker
    - install_docker


- name: "Créer le répertoire /etc/apt/keyrings"
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  tags:
    - docker
    - install_docker

- name: "Télécharger la clé GPG Docker (format ASCII)"
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
  tags:
    - docker
    - install_docker

- name: "Convertir la clé GPG Docker en format keyring"
  ansible.builtin.command:
    cmd: gpg --dearmor -o /etc/apt/keyrings/docker.gpg /etc/apt/keyrings/docker.asc
  args:
    creates: /etc/apt/keyrings/docker.gpg
  tags:
    - docker
    - install_docker

- name: "S'assurer que la clé GPG Docker est lisible"
  ansible.builtin.file:
    path: /etc/apt/keyrings/docker.gpg
    mode: '0644'
  tags:
    - docker
    - install_docker

- name: "Ajouter le dépôt APT Docker"
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch={{ (ansible_architecture == 'x86_64') | ternary('amd64', ansible_architecture) }}
      signed-by=/etc/apt/keyrings/docker.gpg]
      https://download.docker.com/linux/ubuntu
      {{ ansible_lsb.codename }} stable
    filename: docker
    state: present
  tags:
    - docker
    - install_docker

- name: "Installer Docker Engine, CLI, containerd, buildx et plugin compose"
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update-cache: true
  tags:
    - docker
    - install_docker

- name: "Activer et démarrer le service Docker"
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
  tags:
    - docker
    - install_docker

- name: "Ajouter l’utilisateur {{ docker_user }} au groupe docker"
  ansible.builtin.user:
    name: "{{ docker_user }}"
    groups: docker
    append: true
  tags:
    - docker
    - install_docker

- name: "Afficher la version de Docker"
  ansible.builtin.command: docker --version
  register: docker_version_cmd
  changed_when: false
  failed_when: false
  tags:
    - docker
    - install_docker

- name: "Afficher la version de Docker compose (plugin)"
  ansible.builtin.command: docker compose version
  register: docker_compose_version_cmd
  changed_when: false
  failed_when: false
  tags:
    - docker
    - install_docker

- name: "Debug des versions Docker"
  ansible.builtin.debug:
    msg:
      - "Docker : {{ docker_version_cmd.stdout | default('inconnu') }}"
      - "Docker compose : {{ docker_compose_version_cmd.stdout | default('inconnu') }}"
  tags:
    - docker
    - install_docker
