---
# Handlers for docker role

- name: Restart Docker
  systemd:
    name: docker
    state: restarted
  listen: "restart_docker"

- name: Reload Docker daemon
  systemd:
    daemon_reload: yes
  listen: "reload_docker_daemon"
