---
galaxy_info:
  author: DevOps Team
  description: Nginx web server and reverse proxy installation
  company: Portfolio
  license: MIT
  min_ansible_version: '2.9'
  platforms:
    - name: Ubuntu
      versions:
        - '20.04'
        - '22.04'
  tags: [web, reverse-proxy, load-balancer]

dependencies: []
